---
- name: Install Apache
  apt:
    name: apache2
    state: installed
    update_cache: true

- name: Enable common httpd modules
  apache2_module: name={{ item }}
  with_items:
    - rewrite
    - filter
    - deflate
    - headers
    - ssl_module
