---
- name: Install Apache
  apt:
    name: "{{ packages }}"
    state: installed
    update_cache: true
  vars:
    packages:
      - apache2
      - libapache2-mod-php

- name: Enable common httpd modules
  apache2_module: name={{ item }}
  with_items:
    - rewrite
    - filter
    - deflate
    - headers
    - ssl
    - php7.3
